# Configuración de H2 Database
spring.datasource.url=jdbc:h2:mem:sursaluddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola web de H2 para visualizar datos
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate: crear o actualizar las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update